package cz.cvut.fel.omo.semestral.common.enums;

public enum DeviceCommand {
    TURN_ON,
    TURN_OFF,
    ARM_ALARM, DISARM_ALARM, INCREASE_VOLUME, DECREASE_VOLUME, NEXT_CHANNEL, PREVIOUS_CHANNEL, INCREASE_TEMPERATURE, DECREASE_TEMPERATURE, SWITCH_TO_HEATING, SWITCH_TO_COOLING, SWITCH_TO_VENTILATION, TOGGLE_GATE,
}
